export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS_ = 'PRODUCT_LIST_SUCCESS_';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS_ = 'PRODUCT_DETAILS_SUCCESS_'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'